version: '3'
services:
  db:
    container_name: nba-api-db
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nba_api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    container_name: nba-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
